;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-babel-insert-hyphen
        backward-kill-symbolword
        backward-sexp
        backward-symbolword
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-paren
        c-electric-pound
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-hungry-backspace
        comment-dwim
        delete-horizontal-space
        dired-next-line
        dired-previous-line
        ess-smart-comma
        forward-sexp
        forward-symbolword
        haskell-indentation-delete-char
        indent-for-tab-command
        kill-region
        kill-region-or-word-at-point
        kill-symbolword
        markdown-enter-key
        nxml-down-element
        nxml-electric-slash
        sgml-slash
        sh-assignment
        smart-delete-whitespace-backward
        smart-delete-whitespace-forward
        smart-move-beginning-of-line
        sp--self-insert-command
        sp-backward-kill-sexp
        sp-backward-sexp
        sp-forward-sexp
        sp-kill-sexp
        sp-slurp-hybrid-sexp
        sp-splice-sexp
        sp-wrap-tag-done
        tab-to-tab-stop
        typescript-insert-and-indent
        undefined
        undo-tree-visualizer-quit
        vs-move-beginning-of-line
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        dired-clean-directory
        helm-M-x
        indent-whole-buffer
        scroll-down-one
        scroll-up-one
        toggle-input-method
        wdired-change-to-wdired-mode
        wdired-finish-edit
        ))
