;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-babel-insert-hyphen
        backward-kill-symbolword
        backward-sexp
        backward-symbolword
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-hungry-backspace
        comment-dwim
        delete-horizontal-space
        forward-sexp
        forward-symbolword
        haskell-indentation-delete-char
        indent-for-tab-command
        kill-region
        kill-symbolword
        smart-delete-whitespace-backward
        smart-move-beginning-of-line
        sp--self-insert-command
        sp-backward-sexp
        sp-forward-sexp
        sp-slurp-hybrid-sexp
        sp-wrap-tag-done
        tab-to-tab-stop
        vs-move-beginning-of-line
        ))

(setq mc/cmds-to-run-once
      '(
        helm-show-kill-ring
        indent-whole-buffer
        mozc-handle-event
        toggle-input-method
        w3m-goto-alc
        ))
