(custom-set-variables '(recentf-save-file "~/.emacs.d/recentf")
		      '(recentf-max-menu-items 20)
		      '(recentf-max-saved-items 500))
(require 'recentf)
(recentf-mode 1)
(require 'recentf-purge-tramp)
