(require 'helm-config)
(helm-mode 1)
(require 'helm)
(require 'helm-ag-autoloads)
(require 'helm-dired-recent-dirs)
(require 'helm-flymake)
(require 'helm-gist)
(require 'helm-git)
(require 'helm-gtags)
(require 'helm-helm-commands)
(require 'helm-ls-git)

(require 'helm-descbinds)
(helm-descbinds-mode)
